### ISSUE TITLE
Remove username from User model

### ISSUE THREAD

**Issue by aomran** [aomran/curri#1]
One thing I want to implement is the removal of "username" from the User model. This is so that users require as little info as possible to sign up. 

Should we have a profile page somewhere where users can optionally add more info? Like first & last name.

Also the UI currently uses the username in the classrooms view. People see something like this:

`<Username> > Classrooms`

Should I just remove the username part there or replace it with the role (Teacher/Student)? Or do you have another idea?

**Comment by nachiketkumar** [comment]
I like that idea. No need for username in the registration form, only email and pswd.
Optional profile page is also a nice idea, maybe move it down the list in terms of to-dos before sept 16th?

As for page headers: I think we can remove the username from the header, and replace the 'Classrooms' with 'Your Classroooms' to be a little more personal/friendly?

**Comment by pjfranzini** [comment]
At first thought I agree with removing username, is redundant with email as identifier, we want to make sign-up as easy as possible; profile page where can optionally add more info is good too.

'Your Classrooms' sounds better to me than '<role> Classrooms' 

But I think the <Username> going missing needs to be replaced with some indication of who is logged on, maybe not in the same place, perhaps instead on the right-hand side of the menu bar -- I think there is something awkward about the page not saying anything about who is not logged on.

If Email is all we know about them, then it would have to be their email -- perhaps to be replaced by their name if they give it. If we feel it is awkward to identify a person by their email, and we think people may not necessarily want to give and/or display their name, then perhaps this is a sign that we should after all include a username, at least an optional username in the profile page.

**Comment by aomran** [comment]
So I've gone ahead and made the change. https://github.com/aomra015/curry/commit/71aecd7abe24a36c583eb7d0209c5829e13189e2

For displaying information about who's logged in we can do what many apps do and put a symbol in the top right corner (usually it's a gear, a gravatar photo, or a generic picture of a person). Then clicking that pulls down a drop down menu with information about who is logged in as well as a way to access their profile and sign out. Have a look at codecademy, LinkedIn or twitter.

**Comment by pjfranzini** [comment]
That works for me. I prefer codeacademy or LinkedIn style (where they show a mini profile pic) to Twitter where they just show a generic gear (which they can better afford to do than us since they show your name etc. elsewhere).
