### ISSUE TITLE
flash on login page

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#111]
I find the flash message on the login page overkill. It happens only if the user goes to dashboard.curriapp.com or an internal page without being logged in and is redirected to /login, not if you go directly to the /login URL. 

I tried to remove it but it is very important for a lot of tests that I broke, so I put it back.

The login page should be clear enough that it should not need such a basic flash message. If you are trying to access a part of the app without being logged in, you get redirected to the login page, no need for a message. It should be self-explanatory.

If the message is required, to me that's a sign more of work needed on the login screen to make the options clearer.

**Comment by aomran** [comment]
A lot of the notices were added because it's a pattern in Rails to redirect and then give a message. The pattern isn't really a good one in most situations. I can remove this flash message and any tests that check for it.

If there are any other unnecessary messages then lets list them here.

**Comment by nachiketkumar** [comment]
I think we removed the one that wasn't really required- the one after login that told you "you are logged in as _your email address_"

Now we've also removed the one for students toggling help.

I think new class/track/checkpoint created is still justifiable, as are the other ones that are left....

**Comment by aomran** [comment]
As we move more towards a JS front-end with AJAX... the notices become a pattern that we can't use. So we'll have to resort to different ways of visually showing what's happening.

**Comment by aomran** [comment]
Unless we want to start using a front-end notification library but I don't see many apps using them.

**Comment by aomran** [comment]
Fixed in PR #110
