### ISSUE TITLE
Tracks index view

### ISSUE THREAD

**Issue by aomran** [aomran/curri#115]
Tracks index view should be more compact if we're encouraging teachers to use a track as a "lesson". Already the HackerYou classroom has too many boxes and that's just 2 weeks of tracks.

Table view maybe?

**Comment by nachiketkumar** [comment]
I've thought about this too. I don't want to force a list/table view for teachers that don't want to use a track as a lesson. I don't know if in further tests we should encourage it (or discourage- rather see what is more natural). 

Being able to switch from grid view to list view would be one option (basecamp does it, probably for the very same reason, when you have a lot of projects). I also want to indicate somehow which track is 'active', which would depend on setting track start/end times and dates. it could be an 'active' badge, like the 'unpublished' badge.

**Comment by aomran** [comment]
I think it's a good idea early on to let teachers do w/e they want and learn how they actually use the app. Switching between grid and list view might be the better option. I'm not sure how this would be implemented but I assume with CSS one can easily change the view and we'll use JavaScript to toggle the classes.

**Comment by aomran** [comment]
Closing this to move to pivotal tracker.
