### ISSUE TITLE
Long track titles messing up grid

### ISSUE THREAD

**Issue by aomran** [aomran/curri#125]
Implement the change that Nachi suggested for ending long track names with `...` to not mess up the grid.

**Comment by aomran** [comment]
Also there should probably be a minimum height for the grid boxes. When a **classroom** doesn't have the "x pending invitations" and "x unpublished tracks", it becomes shorter than the others and messes up the grid.

My mistake I said "track" earlier.

**Comment by nachiketkumar** [comment]
Good point- this will be required only for the classrooms, not for the tracks.
