### ISSUE TITLE
mobile view requests list

### ISSUE THREAD

**Issue by aomran** [aomran/curri#139]
This is a bug that Brenna talked about. Since the teachers walk around to help students, they use the request list almost exclusively on their mobile. This is what they see 
![screen shot 2014-02-28 at 5 42 18 pm](https://f.cloud.github.com/assets/2048585/2299245/bdb180c0-a0c9-11e3-8401-07c038e7da97.png)

The "yes" button is cut off so it's hard to click.

**Comment by nachiketkumar** [comment]
In portrait mode on the iphone at least (320px width), the yes button is totally invisible.

I had mentioned earlier that we will at some point need a [responsive table solution](http://zurb.com/playground/responsive-tables), so it might be time soon to implement it.

In the meantime, in landscape mode the table is fully visible and not an issue at all.

**Comment by pjfranzini** [comment]
Makes sense to me -- some people tho (Ahmed for example) have their phone locked on portrait mode...

**Comment by aomran** [comment]
Fixed in #141
