### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by aomran** [aomran/curri#2]
For the invitations page.
1. Should the teacher see a list of the people they invited, only the ones who accepted the invitation, or none?
2. Should they be able to add a custom message?
3. How do we make this as painless for the teachers as possible? Imagine having to enter in 30 email addresses or more...

**Comment by pjfranzini** [comment]
1. They should definitely have access to both of these informations, if nothing else by 2 links that open the list of all invited, and the list of all of those that accepted. Or the information could be shown directly on the invitations page, to the side or below
   -- perhaps by listing all invitations, greyed out if haven't accepted, black (or red, or dark blue, etc) if accepted.
   -- perhaps by listing all that have accepted, and links to check all invitations/unaccepted invitations
2. I don't see why it shouldn't be an option; it doesn't have to be a first priority option tho.
3. Could they drag and drop into a box a selection from a file of a list of emails?

**Comment by nachiketkumar** [comment]
1. They should have access to both data, ideally in the same view. Simple table with a column for 'accepted' that can show a red or green circle or a check/cross mark. Other columns could be 'email address', and 'date invited.' 'date accepted' could be a 4th column although I'm not seeing the need for that right now. Perhaps no need for the 'date invited' column either, unless you can think of a good reason to have it?
2. Maybe later, I see no need for this right now. 
3. Two thoughts- first is a form where there are multiple email ID boxes OR you can enter multiple email IDs separated by a comma in the same box (I prefer this latter option). Second- upload a .csv file, but this would probably entail more work on our back end. 

Also, How do we deal with incorrectly entered email IDs or invitations that bounce back due to an error?

**Comment by aomran** [comment]
So I added a table which lists email addresses of students invited along with a status (Pending or Accepted). I also created two css classes with the same names to give them a colour. 

I'm not sure how we keep track of the emails once they're sent. If it's a bad email address then what? Do we really want to tell people if the email address they entered is real or not? It seems this could be abused in some way. I added a validation on the email field, it's currently looking for an "@" symbol. Apparently validating more than that would just be a pain and not really be a good return on the invested time.

**Comment by nachiketkumar** [comment]
Not sure what you mean by "'m not sure how we keep track of the emails once they're sent." Isn't that what the table is doing? As for bad emails and bouncebacks- perhaps that can be dealt with later, as an MVP this should be sufficient.

**Comment by aomran** [comment]
Ok well part of this has been implemented then. Allowing multiple invitations at once will be done next.

**Comment by pjfranzini** [comment]
A regex for recognizing valid email addresses rather than multiple email addresses smushed together (where valid means a set of non-@ characters followed by a single @ character followed by another set of non-characters)
^[^@]+@[^@]+$

**Comment by aomran** [comment]
So if we have a text area where teachers add comma or new-line separated emails then we can process them with this code.

``` ruby
email_array = params[:email].split(/,|\n/)
email_array.each { |email| email.strip! }

email_array.each do |email|
  #create invitation
end
```

**Comment by Peak19** [comment]
In addition to a regex screening process, could we not also include a bounced email notification: 
-- We could add a third status - Pending, Accepted and Failed
-- Is there some way via Mandrill or Postmark API we could trigger this bounced email notification? 

Custom email message: 
-- I think it could be helpful to have a custom email message. Perhaps, the teacher wants to send their own invitation to join the class and how our product will be used by him/her? 
-- We could include a text area for this above the text field for email addresses

If someone drops the class or an email is sent to the wrong person, should we have a way for the teacher to cancel the invitation?

**Comment by aomran** [comment]
- I'm sure that we can hook into the mandrill api and get information about bounced emails but I can't think of an app that does this and I think that's to avoid spam issues. Someone could use our app to identify which email addresses are real.
- Custom email message is easy to add. I'll do like Ali suggested.
- Cancelling invitations or even removing students from a class should be possible. That's a good point.

I actually really like how basecamp does it. They list the people who have been invited with a "Send another invitation" instead of "pending" and there is a "remove" link.

**Comment by aomran** [comment]
As a summary, this issue will be closed once the following has been implemented:
- Allowing multiple invitations at once (with a text area input)
- Allow invitations to be canceled. This pretty much just means destroying the invitation object.

For the beta:
- implement the "Send another invitation" link and sender
- allow custom messages
