### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#4]
Are we implementing 'forgot password' etc features on our user accounts? Can we afford to put this off till later? I think we could put it off unless it is fairly easy to implement- I don't think we're using devise for user accounts, are we? Don't see the gem in the gemfile.

**Comment by aomran** [comment]
Yeah we're not using devise. Paula and I implemented 'forgot password' for the art submission project, so it won't be difficult to adapt that to our needs here.

**Comment by pjfranzini** [comment]
I've just finished implementing it.
