### ISSUE TITLE
Checkpoint form

### ISSUE THREAD

**Issue by aomran** [aomran/curri#5]
So what I ended up doing in the last two commits was add a regular new/edit form for the checkpoints. On the track view there is a button in the top right corner ('Add Checkpoint') and clicking on that takes you to a simple form with two text areas (one for expectation and for success criteria).

The teacher will not see the rating buttons so I've replaced those with "controls". So far there's just an edit link for each checkpoint. Clicking that will take the teacher to pretty much the same form as the one above except this one is for editing.

I didn't want to do anything complicated until at least we saw how the simple ui looks, feels and functions.

**Comment by nachiketkumar** [comment]
A thought- wouldn't it make sense for the teacher to be able to see the previously entered success criteria along with each checkpoint (or lack of one)? Forcing them to click each one to see the popup seems like too much work. For teachers, they need to be able to scan through it quickly and see what's there/what's missing and then go in and edit. Having to click each one doesn't make sense.

Can we implement it such that if user.teacher? show the success criteria as text?

**Comment by aomran** [comment]
We can add an `if else end` block. Show text for teacher, otherwise show the popup thing.

Instead of:

```
<%= content_tag :div, '?', class: 'btn btn-small success-criteria', data: { title: "Success Criteria", content: checkpoint.success_criteria } %>
```

We can use:

```
<% if current_user.student? %>
<%= content_tag :div, '?', class: 'btn btn-small success-criteria', data: { title: "Success Criteria", content: checkpoint.success_criteria } %>
<% else %>
<div><%= checkpoint.success_criteria %></div>
<% end %>
```

**Comment by Peak19** [comment]
Hey guys, I wonder if it might also be possible: 
a) to have each milestone be draggable and droppable (jquery)? I can see teachers quickly want to input information and then sort out the order of events later. Particularly they may want to sort these during class and would need maximum flexibility. 
b) be able to import a word or pdf document (in markup perhaps) and have it sorted automatically into milestones and tracks
c) be able to export their milestones and tracks in a text document for use in other software or for safe-keeping

**Comment by aomran** [comment]
Sorting checkpoints would require an "order" column in the database and then some jQuery on the front-end to do the ordering. I think there is a railscast implementing something similar to what you're talking about.

The import/export of checkpoints seems like a good idea but it will take time to implement properly.

**Comment by nachiketkumar** [comment]
Ali, good points all but I feel that these are all enhancements of features and not necessary for an MVP, which is still what we are building. Let's add to the list of future features, in fact I am going to add a new milestone in Github for future features and add this to it so we can sort all these issues better.

Rather than add new feature ideas to an existing issue (unless it is directly relevant), let's create a new issue to better keep track of things. Ali- would you mind deleting your comment from this issue and opening a new one (and assign the beta launch milestone to it?). Thanks! Not sure if Github allows you to split up an issue into 2 issues.

**Comment by aomran** [comment]
I'm closing this ticket since it doesn't have any specific feature to be implemented.
