### ISSUE TITLE
logged in users

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#6]
I could have sworn there was a discussion to implement a logged in user icon/feature ala linkedin/twitter/codeacademy- where is that gone? Where do we stand on this? I seem to remember reading that it was implemented maybe but I don't see it on my end. I just pulled the recent commits.

**Comment by aomran** [comment]
It's in the README file. This was not implemented.

**Comment by aomran** [comment]
How do we want to implement this? Can you do it Nachi or do you need myself or Paula to do something in the back-end?

**Comment by nachiketkumar** [comment]
let me look into this and get back to you- when are you and Paula heading to Toronto? I imagine that this weekend you will be moving and busy with settling in?

**Comment by aomran** [comment]
We'll be leaving Saturday morning and I'm also going to be very busy the week of the 16th doing hackeryou stuff. So the Alpha launch will most likely need to be pushed back a week or so. Also I should be clear that Heather never confirmed that Curri will be used in the classrooms. So this is something that we still have to convince her and the lead instructor (Wes) of.

**Comment by nachiketkumar** [comment]
Yeah I was pretty sure there was no guarantee of being able to use it in the classroom. But hopefully they will be willing to give it a shot. And if it's used mid-way through the course just for a few modules- that is still great- it will be a good test of whether an approach integrating our app is better/preferable than not, and what could be improved etc. 

If you need me to send Heather a message asking about this, I'm happy to do so- let me know.

**Comment by pjfranzini** [comment]
By the way I was thinking, this feature gives us a quick iconic way to see WHO we are logged in as; it would be nice to at the same time implement an icon next to that one showing WHAT role we are logged in as.

**Comment by nachiketkumar** [comment]
Perhaps just the word in small text below the user's name? I see this feature being important if we start having people using the app who are playing both roles- right? Otherwise you pretty much know what your role is. However just adding the word shouldn't be hard.

**Comment by pjfranzini** [comment]
I agree that a user should tend to know what their role is, yet still like the idea of some indication for transparency. The word in small text below the user's name works for me.
