### ISSUE TITLE
Realtime data

### ISSUE THREAD

**Issue by aomran** [aomran/curri#64]
To get "Realtime" data updates without a browser refresh we're using a Push server (in our case it's Faye). We have:
1. Connection open for teacher on analytics page.
2. Connection open for both teachers and students on all pages to update the # of requesters in header and update the student's help status.

Our Faye server (free on Heroku atm) can probably handle 50 simultaneous connections. Since all of our users have a connection open, that means 50 users that have a browser window open with the Curri app. Scaling Faye is rather complicated so people generally use something like Pusher.com. Their prices are very reasonable.
- Free: 20 simultaneous connections
- $19/month: 100 simultaneous connections  (~19 cents per user)
- $49/month: 500 simultaneous connections  (~10 cents per user)
- $199/month: 5000 simultaneous connections  (~4 cents per user)

As you can see, the money is really not an issue. If we keep our app as is then we just need to keep in mind that every Curri user has a websocket connection open. 

Alternatively we can say that updating the header immediately is not a priority and doesn't warrant "Realtime" treatment. We can leave the realtime just for the teacher analytics. This would mean that the # of websocket connections becomes equal to the # of teachers who are on the analytics page... a much much smaller number.

The # requesters and student status can be updated using something like [polling](http://railscasts.com/episodes/229-polling-for-changes-revised). That means we can make an AJAX request every 1 to 10 seconds to see if the data should be updated. This might be appropriate for data that isn't really meant to be Realtime. I mean even email takes 30 seconds to a few minutes to arrive. 

Any thoughts?

**Comment by pjfranzini** [comment]
I'm fine with this (Ahmed and I discussed this, I was uncomfortable with no update at all, i.e., relying on user refresh of page, but am happy with a polling refresh every 10 sec or so).

**Comment by nachiketkumar** [comment]
I think this is a good compromise. Even if the # requesters were to update in realtime (which is probably at least 1-2 seconds), that only means something if the teacher is sitting there staring at the # to update, which is almost never going to happen. Polling every 10 seconds is fine with me. 

This would leave the realtime feature for teachers on analytics view only, and we could rely on pusher to scale when we have more teachers simultaneously using the app, correct?

**Comment by pjfranzini** [comment]
Notes from meeting: ok to do header info by polling every few seconds. Teacher's requester page should be realtime.
