### ISSUE TITLE
student & teacher views

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#7]
So has the student view been separated entirely? I see the `if current_user.student?` in the _checkpoint.html.erb file. How do I see these controls on the app?

**Comment by aomran** [comment]
If you're logged in as student then you'll see the stuff side the `if current_user.student?` blocks. If you're a teacher then you see stuff inside the `if current_user.teacher?` blocks. So this gives us the flexibility to use the same views for both teacher and student and yet show slightly different things. If the views are going to be completely different then we might need to separate them out.

**Comment by nachiketkumar** [comment]
How does one log in as a student? Is the invitation mailer working etc?

**Comment by aomran** [comment]
The mailer works sort of, check the logs in the terminal for the link.

**Comment by nachiketkumar** [comment]
Oh right. Cool- so for the purposes of design and testing I should be able to create a teacher user and a student user using the link generated by the teacher.

**Comment by aomran** [comment]
Once the student and teacher views have been sorted out we can close this issue.

**Comment by aomran** [comment]
**Moved here**

We can add an `if else end` block. Show text for teacher, otherwise show the popup thing.

Instead of:

```
<%= content_tag :div, '?', class: 'btn btn-small success-criteria', data: { title: "Success Criteria", content: checkpoint.success_criteria } %>
```

We can use:

```
<% if current_user.student? %>
<%= content_tag :div, '?', class: 'btn btn-small success-criteria', data: { title: "Success Criteria", content: checkpoint.success_criteria } %>
<% else %>
<div><%= checkpoint.success_criteria %></div>
<% end %>
```

**Comment by aomran** [comment]
Just to be clear. Student do not have authorization to do anything that only the teacher can do. They get redirected back to the classroom with an error message. The views however are still shared by teacher and student, so we just need to do some cleanup and hide some things if a student is logged in (and vice versa).

**Comment by pjfranzini** [comment]
I'll take charge of this issue.

**Comment by pjfranzini** [comment]
Cleaned up student/teacher views for checkpoints (students do not have edit link for checkpoints, do not have "add checkpoints" button); in classrooms/tracks views no new classroom/track for student, no "invite students" button; no Analytics link on header for students.
