### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#71]
I want to make a basic logo for our app. Right now we only have the wordmark, and I think something simple to go along with it would be nice. 

Any ideas of objects that are representative of our app, or  at least of the main purpose of our app? Don't think too literally...

**Comment by aomran** [comment]
- Antenna
- electromagnetic pulse (squiggly line thing)
- raised hand
- question mark

**Comment by nachiketkumar** [comment]
I really like the idea of an antenna- sending messages, communication etc..

Raised hand is tough to do without looking like a stop symbol, not clearly understood.
Question mark would be representative of a particular feature (ability to ask for help), which isnt the main feature.

I actually like your suggestions in the order you presented them :)

**Comment by Peak19** [comment]
The thoughts that come to mind for me when I think of our App are the following: 
- Maps (as in being able to know where you are at any one time)
- Something living (as in interactive and responsive, versus static, like dead trees on which syllabi are written)
- A speed gauge (as in is the class going too fast or too slow) 
- Communication (as in facilitating dialogue, between diverse groups of people, teachers and students, those who understand and those who don't)
- Echo (as in a teacher speaks and students echo back how well they understood) 
- Breaking down walls (eliminating barriers of communication that were previously there)

**Comment by nachiketkumar** [comment]
I'll do some quick mockups this week of logos and share those on basecamp. So far I think the following have pretty good promise:
- Communication/Antenna
- Map/Compass

**Comment by nachiketkumar** [comment]
Team,

Here's an option for the logo. Keep in mind a few things:
- I don't want to spend ages on the branding at this point- not enough ROI before product validation. Logo is not going to make or break the app (hopefully!!)
- You don't have to absolutely love it right now.
- If warranted, we can rework it later.

This is what I am trying to get across:
- Simple and iconic
- Antenna/pulse
- Communication/echo/something dynamic/listen (I see an ear as well)
- Move forward (directionally it is pointing to the right)
- Incorporate the letter C in there, somewhat subliminally

![curri-logo](https://f.cloud.github.com/assets/3782899/1911306/0b8a6730-7d2a-11e3-94d6-dbc1b8929862.png)

It can't be everything we want to say, brands are built and that is what makes any logo memorable, not the logo in isolation.

I also find the type works much better in lowercase. It's less harsh and formal and more friendly. The typeface is a slightly tweaked version of Calluna Sans Bold. Do we have a good reason for referring to it in all caps and are we OK with referring to it as Curri? Currently all the titles for the pages are spelled this way anyway.

There are numerous wordmarks that are in lowercase while the brand is spelled normally- Facebook, Heroku and Mixpanel to name a few.

Thoughts? If everyone is OK with this I will spend a little more time finessing it and then add this to our app/landing page. I would like to purchase the bold version ($22) and use that legally rather than this version which is a tracing of a screen cap, which is why it looks a little jagged/uneven. You can see what the actual font looks like [here](https://www.fontspring.com/fonts/exljbris/calluna-sans)\- click the test drive tab, choose bold and type in 'curri'.

**Comment by Peak19** [comment]
I really like it Nachi - it is very clear, straightforward and has just enough fun to it. Good for the education market. I think Curri in small caps looks preferable to the dominating look of uppercase. 

I was wondering how the logo would work with color. Is it worth trying a version where each letter is one of our primary colours? 

We will be using a fair amount of colour in our app - from analytics to student ratings. Perhaps, it would be too much to have our app also appear in colour. However, it could also be a good reminder of the deep analytic information we're hoping to provide. It would also be fun. 

Like the direction this took.

**Comment by pjfranzini** [comment]
I like the logo. The sound symbol could even be thought of a c, a u (turned) and the dot on the i.

Perhaps one could try Ali's color idea, just on the three bits of the sound symbol? (eg the dot red, the smaller ( yellow, the outer one green, so it shows understanding growing). Might look weird tho. Another possibility is one color, growing in saturation from the dot to the outside).

one last comment: "(directionally it is pointing to the right)" not for me, since as propagation of the wave it is going to the left

**Comment by nachiketkumar** [comment]
Ali, check out the changes in the master branch- the login pages have our brand colors at the top in a thin bar. The intention behind this addition was to:
- keep user attention near the top of the page and thus the main action of logging in.
- this will make more sense when we have more information in these pages (for example this is the place for a link to the company as well as a privacy policy in a footer), which is secondary information/action items.
- reinforce our brand colors.

Adding colors to the logo as well will be too much, that's not really what we want to draw attention to.

The logo will go at the top, between the sign in box and the brandcolors bar.

I think something fun might be the logo when hovered on can change to a technicolor version :smile:? But not as the main logo.

**Comment by nachiketkumar** [comment]
Paula and Ali, here's a version for you, I think it could work with just this part in color- what say? Do you see growth as left to right (small dot green) or right to left (small dot red)?

Should it be permanently in color or only on hover?

![curri-logo](https://f.cloud.github.com/assets/3782899/1911902/cfa01dc4-7d32-11e3-8080-184da4496349.png)

**Comment by pjfranzini** [comment]
I like the color on hover idea -- one of those cute surprise things. I see growth as small to big, as well as the wave propagation thing, so I like the big ( green best.

**Comment by aomran** [comment]
I really like the logo. I guess colour on hover makes sense to me, you don't really want the logo to be the centre of attention.

**Comment by aomran** [comment]
Also more green seems happier to me.

**Comment by Peak19** [comment]
I have to say I love a little crazy thrown into all the orderliness. The hover idea sounds great. For some reason, I feel like the color would be better used on the word portion of the logo however. 
- I feel like the shape portion should remain indefinable: it could be an antenna, it could be an ear or letters. Color here somehow defines it for me rather than opens it up to possibility.  
- Words on the other hand normally define something precisely and can be overly static. Therefore color here would open it up to possibility, symbolizing to me diversity of ideas perhaps, the excitement and joy of learning.

**Comment by nachiketkumar** [comment]
Final curveball along with Ali's input: what if the icon was reflected? It still reads as forward direction to me, the subliminal C is flipped now but that's not really important.

I've added the word in color. I have to disagree with you Ali, due to the # of colors, I think it works better with the icon. It's simple and adds messaging --> get from red to green. We might have to do a vote on this!

![curri-logo](https://f.cloud.github.com/assets/3782899/1912049/f69f48f8-7d34-11e3-8287-ef83a0bc8359.png)
EDIT: I'm going to go ahead and buy the font I need for this, and wind this up as soon as we come to a decision.

**Comment by aomran** [comment]
So vote on:
- Antenna direction (towards the word or away)
- Colour on text or icon
- Colour on hover or base

I personally like the original antenna direction (away from the word), the colour on the icon (with predominately green) and on hover.

Did I miss something?

**Comment by pjfranzini** [comment]
hmm I wrote a post and cant find it. anyhow:

direction: visually I like the new version, but conceptually think it better to radiate outwards. another possibility: symbol after word, so it can radiate outwards and to the right at the same time?

color: I agree with Nachi that the messaging --> get from red to green is strong. the colored word is fun but doesn't add information.

color: on hover or base -- I'm for hover, tho with it relatively subtle (i.e. just on the symbol) I don't mind either.

**Comment by Peak19** [comment]
You're right Nachi - it doesn't quite work with the number of colors. Unless, the "i" is a mixture of all the colors? Perhaps, in angled stripes?

I'm also partial to the original antennae direction and color on hover.

**Comment by nachiketkumar** [comment]
So I think we have a consensus- option 1 as below, with color on hover.

Option 2 is Paula's suggestion, I'm actually OK with either. It's unusual for the icon to be after the wordmark, but in our case, it also makes sense, use curri to go from red to green etc.

Final call: Option 1 or 2? there are 3 of you, so it can't be a tie :)

![curri-logo](https://f.cloud.github.com/assets/3782899/1912404/bc915674-7d39-11e3-9079-5ef19c2944e2.png)

**Comment by pjfranzini** [comment]
I rather like the second version, tho I am ok with either.

**Comment by aomran** [comment]
I prefer slightly the first version mostly because it looks more symmetrical to me. The antenna feels lower on the other side when it's close to the i.

**Comment by nachiketkumar** [comment]
OK, I have implemented this, check out the logo branch. Had some fun with SVGs :)
