### ISSUE TITLE
Style login page

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#75]
Login page should be styled differently from the app.

**Comment by nachiketkumar** [comment]
What do I need to do so that the login page gets its own structure, i.e is independent of the structure from `application.html.erb`? I don't want the `shared/page_header` and `shared/nav` to render on this page.

**Comment by aomran** [comment]
In the controller action you can add `render layout: "special_layout"` to use the markup in `layouts/special_layout.html.erb` instead of the default `layouts/application.html.erb`

**Comment by aomran** [comment]
To be more specific. Add `render layout: "logout_layout"` to the `new` action in `sessions_controlller.rb`. And then create a `logout_layout.html.erb` in the layouts folder.

**Comment by nachiketkumar** [comment]
Thanks. that works.
