### ISSUE TITLE
Icon for teacher requesters

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#76]
I was thinking a little more about this, and I have some thoughts for better iconography for the requesters:
- We want teachers to strive for helping all the students.
- When a student wants help, that is important and should get the attention of the teacher.
- Color is one way to help in this- we are already using greys for 'all clear' and blue/orange for when help is needed.

I'd like to improve this a little further by:
- Replacing the ? by a (green = success?) smiley face when there are no students needing help.
- Replacing the ? by an ! on orange/red background (plus the # of students on a blue background - flip the colors essentially) when there are students in the queue.

The teacher would then hopefully always want to see a success icon. Thoughts?

**Comment by nachiketkumar** [comment]
See the bugfixes branch, the latest commit has this version.

**Comment by pjfranzini** [comment]
I like this idea.

I also think that the help queue red color for the student is a bit too alarming after all; maybe green or orange would be better.

**Comment by nachiketkumar** [comment]
I am going to change it some more:

Students:
- In help queue to be green --> let's make it a positive action, we want to push this as a key feature, because in our experience this WAS a pain point in our learning experience. Ali had said that as well I think in a previous discussion (about making it positive/calming).

Teachers
- Red seems too alarming here as well, I'm going to make it orange (warning, more appropriate than danger).

**Comment by pjfranzini** [comment]
Sounds good
