### ISSUE TITLE
Weirdness on Requesters page

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#79]
Can anyone else replicate this issue?

On my localhost, I see this:

![screen shot 2014-01-10 at 1 38 30 pm](https://f.cloud.github.com/assets/3782899/1890032/706456b8-7a26-11e3-9b15-dbd301537ad7.png)
- This is very weird, and the line with the student info kept popping in and out, and at one point there were 3 lines for the same student with different times (all today).
- Ima is not saved on my local db, it's only in the production db.
- I was concurrently logged in as the teacher on dashboard.curriapp.com, where 2 students need help- 1 and 2 (alpha and Ima).
- When I logged out as teacher and logged back in on dashboard.c.... the problem stopped.
- I'm scared of Ima magically contacting me from the future.

**Comment by nachiketkumar** [comment]
And now suddenly I saw this: 

![screen shot 2014-01-10 at 2 06 06 pm](https://f.cloud.github.com/assets/3782899/1890288/51556236-7a2a-11e3-8f66-ad39ded5e64b.png)

Well...Ima is back again: 

![screen shot 2014-01-10 at 2 06 47 pm](https://f.cloud.github.com/assets/3782899/1890292/66b47dc4-7a2a-11e3-925a-ed9feb58f012.png)

**Comment by nachiketkumar** [comment]
And now Jane has joined the party too.... WTF!!

![screen shot 2014-01-10 at 2 08 36 pm](https://f.cloud.github.com/assets/3782899/1890304/b2fbcf8e-7a2a-11e3-8992-aa51de0246b0.png)

**Comment by aomran** [comment]
This is because we're all sharing the same Pusher server in development.

**Comment by aomran** [comment]
Our databases are out of sync (unlike the production server, where everyone shares the same database) so that's why you're seeing weird data. If you refresh the page then everything goes back to normal. 

One easy way to fix this is to create different development credentials for each one of us. That way we share separate channels.

**Comment by nachiketkumar** [comment]
Hahah....phew. That makes sense....

**Comment by nachiketkumar** [comment]
As long as I know why, don't bother fixing it. Not a big deal. I can name my students something different in my local db, so I know which ones are mine.

**Comment by pjfranzini** [comment]
yes I saw Liz Student pop up at some point in my tests :)

**Comment by aomran** [comment]
She also freaked out.

**Comment by nachiketkumar** [comment]
:smiley: :ghost:
