### ISSUE TITLE
One Teacher with Multiple Classes

### ISSUE THREAD

**Issue by Peak19** [aomran/curri#8]
Hi guys, will there be any issue with a teacher having one set of tracks and milestones but simultaneously multiple classes of students? 

I suppose we will need to have a Teacher view showing: 
- The multiple classes they are teaching 
- The names of each of these classes (such as HackerYou 2013, Bitmaker 2014 etc) 
- Whether the class is active or completed 

To add a complicating set of factors, do we want to eventually add: 
- Analytics comparing the different class tracks? The teacher, may have used a different teaching style to teach a lecture in each class and wanted to compare which was more effective. 
- The ability to change the order of milestones for a particular class without it changing the order of milestones in all classes.

**Comment by aomran** [comment]
The first part is already implemented; both the student and teacher views start at the classrooms view. There is a list of their classrooms and each one has its name, # of tracks and # of students displayed.

Adding analytics comparing classes could be put on a list of things to do. I'm not sure how much work it would take or if users would use it.

**Comment by aomran** [comment]
I'm going to close this and add your analytics suggestion to the README file.
