### ISSUE TITLE
Adding a feature

### ISSUE THREAD

**Issue by aomran** [aomran/curri#85]
I modified a document from Thoughtbot and added it to our wiki. It pretty much explains the workflow that we should be using for branching. Also note the use of `$ git pull --rebase` to keep a branch up to date and avoid unnecessary merge commits.

https://github.com/aomra015/curri/wiki/Adding-a-Feature

**Comment by aomran** [comment]
If everyone is ok with that then I will delete:
1. https://github.com/aomra015/curri/wiki/Resolving-merge-conflicts
2. https://github.com/aomra015/curri/wiki/Viewing-changes-on-remote-branches

**Comment by pjfranzini** [comment]
Fine with me; the new wiki article clearly includes everything from 1. It includes the essentials from 2; Ali/Nachi should comment if there is anything they still need in (2).

**Comment by nachiketkumar** [comment]
Fine with me- sounds good.
