### ISSUE TITLE
Editing Classroom and Tracks names

### ISSUE THREAD

**Issue by nachiketkumar** [aomran/curri#91]
I've been thinking of the best way to allow editing of classroom and track names. I like how basecamp allows editing of a project title, although I'm not sure how intuitive it is.

I'm inclined to leave it as is right now but perhaps changing midway through the pilot and incorporating the `contenteditable='true'` [attribute](http://html5doctor.com/the-contenteditable-attribute/). Unless I have the time to do it before the invites go out.

The way I imagine this would work is:

For changing classroom name:
- The classroom title on the home page would be editable. Show a save/cancel option when the user starts interacting with it. Only available if teacher.

For changing track details:
- Tracks show would have the name and timings be editable. Again with save/cancel options. Also have the publish/unpublish option here, and show a visual confirmation that the change was accepted. 

This would negate the need for a separate links to edit and edit views for classrooms and tracks, which, especially in the case of classrooms, are very minimal.

It would leave Add Students as the only other link on the tracks index page, and Add checkpoint on the tracks show page.

Thoughts?

**Comment by aomran** [comment]
Yeah I've been thinking about this. It's not urgent but at some point (maybe during the pilot) we can start AJAXifying the UI. There are a few ways of doing this. http://railscasts.com/episodes/302-in-place-editing for example is one option. Lets think about this after the 20th and come up with a good solution.

**Comment by nachiketkumar** [comment]
Nice- this looks promising. I'm going to add this to the pivotal backlog.
